### ISSUE TITLE
Missing 'LoaderFunctionArgs'

### ISSUE THREAD

**Issue by valbaca** [ryanflorence/remix-tutorial-template#4]
Hi, I'm new to Remix and going through the tutorial:

https://remix.run/docs/en/main/start/tutorial

It references LoaderFunctionArgs: https://remix.run/docs/en/main/start/tutorial

That appears to be the latest name for the type.

But the version used in this template still only has `LoaderArgs` available.

I think the fix is to update the version of @remix-run/node but again, I'm new to this so not yet confident enough to make a pull request here.

**Comment by valbaca** [comment]
Here's the text and code from the tutorial:


Validating Params and Throwing Responses
TypeScript is very upset with us, let's make it happy and see what that forces us to consider:

```
import type { LoaderFunctionArgs } from "@remix-run/node";
// existing imports
import invariant from "tiny-invariant";

// existing imports

export const loader = async ({
  params,
}: LoaderFunctionArgs) => {
  invariant(params.contactId, "Missing contactId param");
  const contact = await getContact(params.contactId);
  return json({ contact });
};

// existing code
```

**Comment by ghost** [comment]
If you take a loot at `package.json` file, you'll see that remix packages (like `@remix-run/node`) are on version `nightly`, try running `npx upgrade-remix` to update to the `latest` tag on NPM, which in this case is version `2.0.0`.

Hope this fixes your problem.

**Comment by valbaca** [comment]
Thanks!
